### ISSUE TITLE
[Documentation] UML

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/astobj#1]
@Ranplax, how about moving the UML diagram to the [`backlog`](https://github.com/StarSimVR/backlog)?

**Comment by NiklasLeukroth** [comment]
The UML diagram was just to showcase the idea and will not be maintained any further, hence i would prefer removing it entirely, rather then moving it into the backlog

**Comment by kevinmatthes** [comment]
Since the backlog is about the documentation, also about the initial ideas, I thought moving the concept UML diagram would be a good idea.  But you are free to delete it, anyway.

However, please close this issue when you finished moving / deleting this file.

**Comment by NiklasLeukroth** [comment]
In general i would be open to having an uml diagram showcasing the dependencies in the future, however, we should first implement a stable version of the code. I will reopen the issue, once this is achieved.
