### ISSUE TITLE
[Discussion] Build Routine

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/astobj#2]
Would you prefer GNU Octave scripts or `justfile`s for the build routine, @Ranplax and @Luka-sama?

It is just a matter of taste but maybe the `justfile`s enhance the portability since they bring a shell expansion feature on their own...  On the other hand, `just` requires Rust and, thus, new dependencies.

**Comment by NiklasLeukroth** [comment]
We should definitely avoid further increasing out dependencies, so just reusing the build routine provided in the Rnfpp repo should suffice

**Comment by kevinmatthes** [comment]
Okay, thanks!
