### ISSUE TITLE
[Bug] ‘GodotObject’ has not been declared

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/astobj#4]
@Ranplax, where do you take the `GodotObject` type from for `Controller.hpp`?  There is no such definition in the project...

**Comment by NiklasLeukroth** [comment]
Yes, i am aware, at the time of creation i used this as a placeholder, since i was not sure, what the interface between godot and c++ looks like

**Comment by kevinmatthes** [comment]
@Luka-sama, do you know which data structure of the `godot-cpp/godot-headers` submodule should be used therefore?

**Comment by NiklasLeukroth** [comment]
Don't worry about it for now, i will most likely rewrite the Controller in native GDScript and have the objects that are to be monitored as children of the controller node. Hence, this issue will become obsolete with the next resturcture.

**Comment by kevinmatthes** [comment]
So, basically, the Controller implementation -- the header and the source file -- can be savely deleted, right?  The project does not compile since the compiler cannot locate the definition of the queried data structure.

**Comment by NiklasLeukroth** [comment]
Let's wait until i actually implement it, but yes, deleting these files is the plan going forward
