### ISSUE TITLE
Fix the math

### ISSUE THREAD

**Issue by NiklasLeukroth** [StarSimVR/astobj#6]
The underlying math seems to be a little bit off right now.

**Comment by NiklasLeukroth** [comment]
The math has been improved significantly while cutting down the time complexity by the factor 2. The system is currently relativly stable, altough planets do spin out of orbit, which indicates another problem, that has yet to be identified

**Comment by kevinmatthes** [comment]
Does the problem occur relatively deterministically, i. e. after a certain amount of time has passed, or is there no real temporal trigger, indicating a rather random behaviour?

Did you try to let the application write some debug logging?  What information are shown?

**Comment by kevinmatthes** [comment]
The participating dimensions -- acceleration, velocity, and position -- depend on each other by a system of differential equations.  Which equations and system do you use at the moment, @Ranplax?  And how is it solved?

**Comment by NiklasLeukroth** [comment]
The equations used are the following and are solved in this order for each element in the scene. Note that the formula $\frac{G * m_j}{r^2}$ differs from the conventional formula of gravity by Newton, because the acceleration $a$ is $\frac{\vec{F}}{m_i}$.

$r^2$ describes the distance squared between the objects.

$$a_{i, new} = \sum_{j \neq i} \frac{pos_j - pos_i}{||pos_j - pos_i||_2} * \frac{G * m_j}{r^2}$$

$$v_{i, new} = v_{i, old} + a_{i, new}$$

$$pos_{i, new} = pos_{i, old} + v_{i, new}$$

**Comment by kevinmatthes** [comment]
In physics, the static equations for movements with constant accelerations are as follows:

$$
\boldsymbol x (t) = \frac {\boldsymbol a (t)} 2 \cdot t ^ 2 + \boldsymbol v_0 \cdot t + \boldsymbol x_0
$$

$$
\boldsymbol v (t) = \boldsymbol a (t) \cdot t + \boldsymbol v_0
$$

The initial position, $\boldsymbol x_0$, as well as the initial velocity, $\boldsymbol v_0$, are for each succeeding time slice the respective values from before the updates.  What would happen if you would implement the following update procedure for velocity and position?

$$
t := \langle \textrm {duration of the last frame} \rangle
$$

$$
\boldsymbol v := \boldsymbol a \cdot t + \boldsymbol v_0
$$

$$
\boldsymbol x := \frac {\boldsymbol a} 2 \cdot t ^ 2 + \boldsymbol v \cdot t + \boldsymbol x_0
$$

**Comment by NiklasLeukroth** [comment]
So, i don't think the results fix the simulation completely, but it improves it significantly and the remaining errors may be in rounding or the starting positions, which i will see to later. 
I am going to present this change in our meeting later and you can see for yourself, thanks.

**Comment by kevinmatthes** [comment]
Does a reduction of the mass parameter bring further enhancements?

**Comment by kevinmatthes** [comment]
I am going to add a query of the current FPS rate to the maths.  This might fix this issue.  I will base my changes on #7.

**Comment by NiklasLeukroth** [comment]
Fixed
